name: Go
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get go toolchains
      run: |
        go get -u golang.org/x/tools/cmd/goimports
        sudo cp $GOPATH/bin/goimports /usr/bin/
      env:
        GOPATH: /home/runner/work/suez/go

    - name: Check
      run: make ci-check
      env:
        GOPATH: /home/runner/work/suez/go

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.29


